package com.sain.goodlife.api.entity.po.shiro;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * ShiroRolesPermissionsT1Id generated by hbm2java
 */
public class ShiroRolesPermissionsIdPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long roleId;
	private long permissionId;

	public ShiroRolesPermissionsIdPoEntity() {
	}

	public ShiroRolesPermissionsIdPoEntity(long roleId, long permissionId) {
		this.roleId = roleId;
		this.permissionId = permissionId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public long getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(long permissionId) {
		this.permissionId = permissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShiroRolesPermissionsIdPoEntity))
			return false;
		ShiroRolesPermissionsIdPoEntity castOther = (ShiroRolesPermissionsIdPoEntity) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getPermissionId() == castOther.getPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRoleId();
		result = 37 * result + (int) this.getPermissionId();
		return result;
	}

}
