package com.sain.goodlife.api.entity.po.shiro;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * ShiroPermissionsT1 generated by hbm2java
 */
public class ShiroPermissionsPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;
	private String permission;
	private String description;
	private Boolean isAvailable;

	public ShiroPermissionsPoEntity() {
	}

	public ShiroPermissionsPoEntity(long id) {
		this.id = id;
	}

	public ShiroPermissionsPoEntity(long id, String permission, String description,
			Boolean isAvailable) {
		this.id = id;
		this.permission = permission;
		this.description = description;
		this.isAvailable = isAvailable;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

}
