package com.sain.goodlife.api.entity.po.shiro;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * ShiroUsersRolesT1Id generated by hbm2java
 */
public class ShiroUsersRolesIdPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long userId;
	private long roleId;
	private byte userType;

	public ShiroUsersRolesIdPoEntity() {
	}

	public ShiroUsersRolesIdPoEntity(long userId, long roleId, byte userType) {
		this.userId = userId;
		this.roleId = roleId;
		this.userType = userType;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public byte getUserType() {
		return this.userType;
	}

	public void setUserType(byte userType) {
		this.userType = userType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShiroUsersRolesIdPoEntity))
			return false;
		ShiroUsersRolesIdPoEntity castOther = (ShiroUsersRolesIdPoEntity) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getRoleId() == castOther.getRoleId())
				&& (this.getUserType() == castOther.getUserType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getRoleId();
		result = 37 * result + this.getUserType();
		return result;
	}

}
