package com.sain.goodlife.api.entity.po.shiro;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * ShiroUsersRolesT1 generated by hbm2java
 */
public class ShiroUsersRolesPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private ShiroUsersRolesIdPoEntity id;
	private String userFrom;

	public ShiroUsersRolesPoEntity() {
	}

	public ShiroUsersRolesPoEntity(ShiroUsersRolesIdPoEntity id) {
		this.id = id;
	}

	public ShiroUsersRolesPoEntity(ShiroUsersRolesIdPoEntity id, String userFrom) {
		this.id = id;
		this.userFrom = userFrom;
	}

	public ShiroUsersRolesIdPoEntity getId() {
		return this.id;
	}

	public void setId(ShiroUsersRolesIdPoEntity id) {
		this.id = id;
	}

	public String getUserFrom() {
		return this.userFrom;
	}

	public void setUserFrom(String userFrom) {
		this.userFrom = userFrom;
	}

}
