package com.sain.goodlife.api.entity.po.shiro;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * ShiroRolesT1 generated by hbm2java
 */
public class ShiroRolesPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;
	private String role;
	private String description;
	private Boolean isAvailable;

	public ShiroRolesPoEntity() {
	}

	public ShiroRolesPoEntity(long id) {
		this.id = id;
	}

	public ShiroRolesPoEntity(long id, String role, String description,
			Boolean isAvailable) {
		this.id = id;
		this.role = role;
		this.description = description;
		this.isAvailable = isAvailable;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

}
