package com.sain.goodlife.api.entity.po.user;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * AdminT1 generated by hbm2java
 */
public class AdminPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;
	private String AUsername;
	private String APassword;
	private String salt;
	private Boolean isLocked;

	public AdminPoEntity() {
	}

	public AdminPoEntity(long id) {
		this.id = id;
	}

	public AdminPoEntity(long id, String AUsername, String APassword, String salt,
			Boolean isLocked) {
		this.id = id;
		this.AUsername = AUsername;
		this.APassword = APassword;
		this.salt = salt;
		this.isLocked = isLocked;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getAUsername() {
		return this.AUsername;
	}

	public void setAUsername(String AUsername) {
		this.AUsername = AUsername;
	}

	public String getAPassword() {
		return this.APassword;
	}

	public void setAPassword(String APassword) {
		this.APassword = APassword;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public Boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

}
