package com.sain.goodlife.api.entity.po.user;

import com.sain.goodlife.api.entity.po.PoEntity;

// Generated 2014-5-27 15:50:26 by Hibernate Tools 4.0.0

/**
 * UsersT1 generated by hbm2java
 */
public class UsersPoEntity implements PoEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;
	private String username;
	private String password;
	private String salt;
	private Boolean locked;

	public UsersPoEntity() {
	}

	public UsersPoEntity(long id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public UsersPoEntity(long id, String username, String password, String salt,
			Boolean locked) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.locked = locked;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

}
